services:
  fossic-api:
    build: .
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./src:/app
    env_file:
      - .env
    networks:
      - default
      - forum-db

networks:
  forum-db:
    external: true
    name: fossicdiscuz_fossic-forum
